version: "v1"

services:
  mysql:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      env_file:
        - .env
      ports:
        - '3306:3306'
      volumes:
        - db:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    env_file:
      - .env
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
      - ./media:/app/media
    restart: always
    links:
      - mysql

volumes:
  db:
    driver: local